*** Variables ***
${BTN_PROJECT}        id=com.sinognss.sm.free:id/fixed_bottom_navigation_title
${BTN_CLOUD_SERVICE}  android=new UiSelector().className("android.widget.TextView").text("云服务")
${BTN_USER_SELECT}    id=com.sinognss.sm.free:id/txt_username
${INPUT_USERNAME}     id=com.sinognss.sm.free:id/txt_username
${INPUT_PASSWORD}     id=com.sinognss.sm.free:id/txt_password
${BTN_LOGIN}          id=com.sinognss.sm.free:id/btn_login
${BTN_PASSWORD_SELECT}    id=com.sinognss.sm.free:id/txt_password
